name: telos
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10
  - joblib
  - lightgbm
  - numpy
  - pandas
  - pysam
  - pyyaml
  - scikit-learn
  - xgboost
  - pip
  - setuptools
